---
title: "Nestedness"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}

library(vegan)

```

### Read in necessary files

```{r}

# presence absence matrices from data rarefied at the plot level
rare_ro_mat_pa <- readRDS("../intermediate_files/rds/rare_ro_mat_pa.rds")
rare_ak_mat_pa <- readRDS("../intermediate_files/rds/rare_ak_mat_pa.rds")


```

For the nestedness plots, we use rarefied data (sequencing depth normalized by plot).


```{r}

# transpose presence absence matrices so that hosts are rows, ASVs are columns

nestedness_ro_mat <- t(rare_ro_mat_pa)

nestedness_ak_mat <- t(rare_ak_mat_pa)


# calculate nested temp and nodf on a presence absence matrix with hosts as rows, ASVs as columns

ro_nest_temp <- nestedtemp(nestedness_ro_mat)

ro_nodf <- nestednodf(nestedness_ro_mat)
  
ak_nest_temp <- nestedtemp(nestedness_ak_mat)

ak_nodf <- nestednodf(nestedness_ak_mat)


# nestedness plot - names argument shows row names, hides col names
plot(veg_nest_ak, names = c(TRUE, FALSE), kind="incidence", col=c("white", "grey"))


# determine significance of nestedness temperature using method "quasiswap" which maintains species and row frequencies, compared against 1000 randomized null communities

ro_nest_signif <- oecosimu(nestedness_ro_mat, nestedtemp, "quasiswap", nsimul = 1000)

ro_nodf_signif <- oecosimu(nestedness_ro_mat, nestednodf, "quasiswap", nsimul = 1000)


ak_nest_signif <- oecosimu(nestedness_ak_mat, nestedtemp, "quasiswap", nsimul = 1000)

ak_nodf_signif <- oecosimu(nestedness_ak_mat, nestednodf, "quasiswap", nsimul = 1000)




# Plot

pdf("figures/nestedness3.pdf")

par(mfrow=c(2,1), mai=c(0.5,1.6,0.7,0.5), oma=c(0.1, 0.5, 0.5, 0.5))

plot(ro_nest_temp, names = c(TRUE, FALSE), kind="incidence", col=c("white", "grey"))
title(main="A)", adj=0)
title(main="Remnant Forest")

#mtext("Nested Temp=34.6, P=0.612, NODF=31.8, P=0.159")

plot(ak_nest_temp, names = c(TRUE, FALSE), kind="incidence", col=c("white", "grey"))
title(main="B)", adj=0)
title(main="Restored Forest")

#mtext("Nested Temp=37.3, P=0.001, NODF=30.4, P=0.001")

dev.off()



# Plot

pdf("figures/nestedness3.pdf")

par(mfrow=c(2,1), mai=c(0.5,1.6,0.7,0.5), oma=c(0.1, 0.5, 0.5, 0.5))

par(mar=c(1,7,2,1))

plot(ro_nest_temp, names = c(TRUE, FALSE), kind="incidence", col=c("white", "grey"))
title(main="A)", adj=0)
title(main="Remnant Forest")

#mtext("Nested Temp=34.6, P=0.612, NODF=31.8, P=0.159")

par(mar=c(0.5,7,2,1))

plot(ak_nest_temp, names = c(TRUE, FALSE), kind="incidence", col=c("white", "grey"))
title(main="B)", adj=0)
title(main="Restored Forest")

#mtext("Nested Temp=37.3, P=0.001, NODF=30.4, P=0.001")

dev.off()

```


