---
title: "UpSet"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}

library(ComplexUpset)
library(ggplot2)

```


### Read in necessary files

```{r}

# presence absence matrices from data rarefied at the plot level
rare_ro_mat_pa <- readRDS("../intermediate_files/rds/unrare_ro_mat_pa.rds")
rare_ak_mat_pa <- readRDS("../intermediate_files/rds/unrare_ak_mat_pa.rds")

# a vector of host names + soil
host_names <- readRDS("../intermediate_files/rds/host_names.rds")

```


```{r}

# convert presence absence matrices to data frames
ro_upset_df <- as.data.frame(unrare_ro_mat_pa)

ak_upset_df <- as.data.frame(unrare_ak_mat_pa)


# Generate upset plot with percentage labels
# change min_size to only show intersections >1%
# this makes a double plot with both ak and ro
upset_ro_ak <-
  upset(
  ro_upset_df, 
  host_names, 
  name = '',
  min_size=11,
  width_ratio = 0.2,
  wrap = TRUE,
  set_sizes=FALSE,
  base_annotations = list(
    'Intersection size'=intersection_size(
      text=list(size=3, vjust=-0.5), 
      text_aes = aes(
      label=paste0(signif(intersection_size/nrow(ro_upset_df) * 100, digits=2), '%')))), 
  themes = upset_modify_themes(
    list(
        'Intersection size'=theme(
          panel.grid.major=element_blank(), 
          panel.grid.minor=element_blank(),
          axis.line = element_line(colour="gray")),
        'intersections_matrix'=theme(text=element_text(face='italic'))
      )
    )
  ) + ggtitle('A) Remnant Forest') + 
  upset(
  ak_upset_df, 
  host_names, 
  name = '',
  min_size=11,
  width_ratio = 0.2,
  wrap = TRUE,
  set_sizes=FALSE,
  base_annotations = list(
    'Intersection size'=intersection_size(
      text=list(size=3, vjust=-0.5), 
      text_aes = aes(
      label=paste0(signif(intersection_size/nrow(ak_upset_df) * 100, digits=2), '%')))), 
  themes = upset_modify_themes(
    list(
        'Intersection size'=theme(
          panel.grid.major=element_blank(), 
          panel.grid.minor=element_blank(),
          axis.line = element_line(colour="gray")),
        'intersections_matrix'=theme(text=element_text(face='italic'))
      )
    )
  ) + ggtitle('B) Restored Forest')
  

  
# plot
pdf("figures/upset.pdf", width=16, height=5, onefile = F)
upset_ro_ak
dev.off()


```


```{r}

# this version shows all intersections

ak_upset_full <- 
  upset(
  ak_upset_df, 
  host_names, 
  name = '',
  min_size=1,
  width_ratio = 0.1,
  base_annotations = list(
    'Intersection size'=intersection_size(
      text=list(size=3, vjust=-0.1, hjust=0, angle=60), 
      text_aes = aes(
      label=paste0(signif(intersection_size/nrow(ak_upset_df) * 100, digits=2), '%')))), 
  themes = upset_modify_themes(
    list(
        'Intersection size'=theme(
          panel.grid.major=element_blank(), 
          panel.grid.minor=element_blank(),
          axis.line = element_line(colour="gray"))
      )
    )
  )

ggsave("../figures/ak_upset_full.pdf", width = 24, height = 5)

```


