---
title: "ANOVA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}

library(tibble)
library(tidyr)
library(reshape2)
library(plyr)
library(dplyr)

```

### Read in necessary files

```{r}

# vector of host names and soil
host_names <- readRDS("../intermediate_files/rds/host_names.rds")

# list of unrarefied physeq objects by host and soil
unrarefied_subsets <- readRDS("../intermediate_files/rds/unrarefied_subsets.rds")

# lists of relative abundance data frames for our three groupings
ro_unique_asvs <- readRDS("../intermediate_files/rds/ro_unique_asvs.rds")
ak_unique_asvs <- readRDS("../intermediate_files/rds/ak_unique_asvs.rds")


ro_shared_asvs <- readRDS("../intermediate_files/rds/ro_shared_asvs.rds")
ak_shared_asvs <- readRDS("../intermediate_files/rds/ak_shared_asvs.rds")


ro_soil_host_asvs <- readRDS("../intermediate_files/rds/ro_soil_host_asvs.rds")
ak_soil_host_asvs <- readRDS("../intermediate_files/rds/ro_soil_host_asvs.rds")

```


## Data Prep

```{r}

# make one big full otu table (plots still separate) to calculate rel abun on
# later on just subset as needed

source("../src/anova_functions.R")

### arguments for this function include:
# vector of host names
# list of unrarefied physeq objects
# relative abundance data frames for each habitat for the specific grouping (unique, # shared, soil-host)

unique_otu_tables <- lapply(host_names, 
                         otu_table_prep, 
                         unrarefied_subsets,
                         ro_unique_asvs,
                         ak_unique_asvs)

names(unique_otu_tables) <- host_names


```


```{r}

# make a copy of the otu tables
rel_abun_by_host <- unique_otu_tables

# make a vector of all the family names in that grouping
family_names <- c("Acaulosporaceae",
                  "Ambisporaceae",
                  "Archaeosporaceae",
                  "Claroideoglomeraceae",
                  "Diversisporaceae", 
                  "Geosiphonaceae",
                  "Gigasporaceae",
                  "Glomeraceae",
                  "Glomeromycotina",
                  "Paraglomeraceae")


### arguments for this function:
# vector of host names


host_relabun_by_family <- lapply(host_names, anova_prep, unique_otu_tables)

names(host_relabun_by_family) <- host_names



host_relabun_by_family[["A. koa"]] <- host_relabun_by_family[["A. koa"]] %>%
  select(!(Diversisporaceae:Gigasporaceae))

host_relabun_by_family[["C. trigynum"]] <- host_relabun_by_family[["C. trigynum"]] %>%
  select(!(Claroideoglomeraceae:Geosiphonaceae))

host_relabun_by_family[["Grass"]] <- host_relabun_by_family[["Grass"]] %>%
  select(!(Diversisporaceae:Geosiphonaceae))

host_relabun_by_family[["M. lessertiana"]] <- host_relabun_by_family[["M. lessertiana"]] %>%
  select(!(Diversisporaceae))

host_relabun_by_family[["R. hawaiensis"]] <- host_relabun_by_family[["R. hawaiensis"]] %>%
  select(!(Diversisporaceae:Gigasporaceae))



unique_lm_all <- list()

# runs a linear model for each family in each host
# returns a list corresponding to host containing lists corresponding to families
# aka parent lists are hosts, inner lists are families
for (a_host in host_names) {
  lm_apply <- lapply(family_names,
                     run_lm,
                     lm_abun = host_relabun_by_family[[a_host]])
  unique_lm_all[[a_host]] <- lm_apply
  names(unique_lm_all[[a_host]]) <- family_names
}



unique_lm_all <- lapply(host_names, null_remove, unique_lm_all)

names(unique_lm_all) <- host_names




unique_lm_aov <- list()
 
for (a_host in host_names) {
  aov_on_lm <- lapply(family_names,
                      summarize_lm,
                      lm_out = unique_lm_all[[a_host]])
  unique_lm_aov[[a_host]] <- aov_on_lm
  names(unique_lm_aov[[a_host]]) <- family_names
}



unique_lm_aov <- lapply(host_names, null_to_na, unique_lm_aov)

names(unique_lm_aov) <- host_names



unique_family_stats <- as.data.frame(do.call("rbind", unique_lm_aov))

unlisted_families <- list()

for (a_host in host_names) {
  unlisted_lists <- unlist(unique_lm_aov[[a_host]])
  unlisted_families[[a_host]] <- unlisted_lists
}

# combine vectors into one data frame
unique_anova_p_vals <- as.data.frame(do.call("rbind", unlisted_families))




unique_pval_table <- anova_tbl_format(unique_anova_p_vals)

rownames(unique_pval_table) <- family_names



write.csv(unique_pval_table, file="../outputs/unique_anova_pvals.csv")


```


## Shared ASVs

```{r}

shared_otu_tables <- lapply(host_names, 
                         otu_table_prep, 
                         unrarefied_subsets,
                         ro_shared_asvs,
                         ak_shared_asvs)

names(shared_otu_tables) <- host_names



shared_abun_by_host <- shared_otu_tables

shared_family_names <- c("Acaulosporaceae",
                        "Ambisporaceae",
                        "Archaeosporaceae",
                        "Claroideoglomeraceae",
                        "Gigasporaceae",
                        "Glomeraceae",
                        "Glomeromycotina",
                        "Paraglomeraceae")





shared_abun_by_family <- lapply(host_names, anova_prep, shared_otu_tables)

names(shared_abun_by_family) <- host_names



host_relabun_by_family[["A. koa"]] <- host_relabun_by_family[["A. koa"]] %>%
  select(!(Diversisporaceae:Gigasporaceae))

host_relabun_by_family[["C. trigynum"]] <- host_relabun_by_family[["C. trigynum"]] %>%
  select(!(Claroideoglomeraceae:Geosiphonaceae))

host_relabun_by_family[["Grass"]] <- host_relabun_by_family[["Grass"]] %>%
  select(!(Diversisporaceae:Geosiphonaceae))

host_relabun_by_family[["M. lessertiana"]] <- host_relabun_by_family[["M. lessertiana"]] %>%
  select(!(Diversisporaceae))

host_relabun_by_family[["R. hawaiensis"]] <- host_relabun_by_family[["R. hawaiensis"]] %>%
  select(!(Diversisporaceae:Gigasporaceae))



shared_lm_all <- list()

# runs a linear model for each family in each host
# returns a list corresponding to host containing lists corresponding to families
# aka parent lists are hosts, inner lists are families
for (a_host in host_names) {
  lm_apply <- lapply(shared_family_names,
                     run_lm,
                     lm_abun = shared_abun_by_family[[a_host]])
  shared_lm_all[[a_host]] <- lm_apply
  names(shared_lm_all[[a_host]]) <- shared_family_names
}





shared_lm_aov <- list()
 
for (a_host in host_names) {
  aov_on_lm <- lapply(shared_family_names,
                      summarize_lm,
                      lm_out = shared_lm_all[[a_host]])
  shared_lm_aov[[a_host]] <- aov_on_lm
  names(shared_lm_aov[[a_host]]) <- shared_family_names
}




shared_family_stats <- as.data.frame(do.call("rbind", shared_lm_aov))

shared_unlisted_families <- list()

for (a_host in host_names) {
  unlisted_lists <- unlist(shared_lm_aov[[a_host]])
  shared_unlisted_families[[a_host]] <- unlisted_lists
}

# combine vectors into one data frame
shared_anova_p_vals <- as.data.frame(do.call("rbind",
                                             shared_unlisted_families))




shared_pval_table <- anova_tbl_format(shared_anova_p_vals)

rownames(shared_pval_table) <- shared_family_names


write.csv(shared_pval_table, file="../outputs/shared_anova_pvals.csv")

```


## Soil Host ASVs

```{r}

soho_otu_tables <- lapply(host_names_no_soil, 
                         otu_table_prep, 
                         unrarefied_subsets,
                         ro_soil_host_asvs,
                         ak_soil_host_asvs)

names(soho_otu_tables) <- host_names_no_soil



soho_abun_by_host <- soho_otu_tables

soho_family_names <- c("Acaulosporaceae",
                        "Ambisporaceae",
                        "Archaeosporaceae",
                        "Claroideoglomeraceae",
                        "Diversisporaceae",
                        "Gigasporaceae",
                        "Glomeraceae",
                        "Glomeromycotina",
                        "Paraglomeraceae")





soho_abun_by_family <- lapply(host_names_no_soil, anova_prep, soho_otu_tables)

names(soho_abun_by_family) <- host_names_no_soil



hosts_no_diversi <- c("C. trigynum",
                      "Grass",
                      "M. polymorpha",
                      "M. lessertiana")


for (a_host in hosts_no_diversi) {
  
  soho_abun_by_family[[a_host]] <-
    soho_abun_by_family[[a_host]] %>%
    select(!(Diversisporaceae))
  
}




soho_lm_all <- list()

# runs a linear model for each family in each host
# returns a list corresponding to host containing lists corresponding to families
# aka parent lists are hosts, inner lists are families
for (a_host in host_names_no_soil) {
  lm_apply <- lapply(soho_family_names,
                     run_lm,
                     lm_abun = soho_abun_by_family[[a_host]])
  soho_lm_all[[a_host]] <- lm_apply
  names(soho_lm_all[[a_host]]) <- soho_family_names
}


soho_lm_all <- lapply(host_names_no_soil, null_remove, soho_lm_all)

names(soho_lm_all) <- host_names_no_soil




soho_lm_aov <- list()
 
for (a_host in host_names) {
  aov_on_lm <- lapply(soho_family_names,
                      summarize_lm,
                      lm_out = soho_lm_all[[a_host]])
  soho_lm_aov[[a_host]] <- aov_on_lm
  names(soho_lm_aov[[a_host]]) <- soho_family_names
}



soho_lm_aov <- lapply(host_names_no_soil, null_to_na, soho_lm_aov)

names(soho_lm_aov) <- host_names_no_soil




soho_family_stats <- as.data.frame(do.call("rbind", soho_lm_aov))

soho_unlisted_families <- list()

for (a_host in host_names) {
  unlisted_lists <- unlist(soho_lm_aov[[a_host]])
  soho_unlisted_families[[a_host]] <- unlisted_lists
}

# combine vectors into one data frame
soho_anova_p_vals <- as.data.frame(do.call("rbind",
                                             soho_unlisted_families))




soho_pval_table <- anova_tbl_format(soho_anova_p_vals)

rownames(soho_pval_table) <- soho_family_names


write.csv(soho_pval_table, file="../outputs/soho_anova_pvals.csv")

```


## Interleaving relabun tables with p values

```{r}

merged_unique_relabun

merged_shared_relabun

merged_soil_host_relabun


host_index <- c(1,2,15,
               3,4,16,
               5,6,17,
               7,8,18,
               9,10,19,
               11,12,20,
               13,14,21)

host_nosoil_index <- c(1,2,13,
                       3,4,14,
                       5,6,15,
                       7,8,16,
                       9,10,17,
                       11,12,18)


merge_relabun_pval <- function (relabun_table, pval_table, index) {
  
  merged_table <- merge(relabun_table, pval_table, by="row.names")
  
  merged_table <- column_to_rownames(merged_table, "Row.names")
  
  merged_table <- merged_table[, index]
  
  colnames(merged_table)[seq(3, ncol(merged_table), 3)] <- "P"
  
  return(merged_table)
  
}


final_unique_table <- merge_relabun_pval(merged_unique_relabun,
                                         unique_pval_table,
                                         host_index)

final_shared_table <- merge_relabun_pval(merged_shared_relabun,
                                         shared_pval_table,
                                         host_index)

final_soho_table <- merge_relabun_pval(merged_soil_host_relabun,
                                       soho_pval_table,
                                       host_nosoil_index)



write.csv(final_unique_table, "../outputs/unique_relabun_pval.csv")

write.csv(final_shared_table, "../outputs/shared_relabun_pval.csv")

write.csv(final_soho_table, "../outputs/soil_host_relabun_pval.csv")

```




