---
title: "Relative Abundance Tables"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

To break down the family membership of ASVs by host and habitat.

## Libraries

```{r}

library(reshape2)
library(dplyr)
library(tibble)

```

## Things Needed

```{r}

# data frames of unique ASVs
ro_unique_rbind <- readRDS("../intermediate_files/rds/ro_unique_rbind.rds")
ak_unique_rbind <- readRDS("../intermediate_files/rds/ak_unique_rbind.rds")

# data frames of shared ASVs
ro_shared_rbind <- readRDS("../intermediate_files/rds/ro_shared_rbind.rds")
ak_shared_rbind <- readRDS("../intermediate_files/rds/ro_shared_rbind.rds")

# data frames of soil host ASVs
ro_soil_host_rbind <- 
  readRDS("../intermediate_files/rds/ro_soil_host_rbind.rds")
ak_soil_host_rbind <-
  readRDS("../intermediate_files/rds/ak_soil_host_rbind.rds")

# matrix of ASV counts by host
unrare_ro_full_mat <- 
  readRDS("../intermediate_files/rds/unrare_ro_full_mat.rds")

# matrix of ASV counts by host
unrare_ak_full_mat <- 
  readRDS("../intermediate_files/rds/unrare_ak_full_mat.rds")

```

## Unique

```{r}

# make new copy of unique ak df
ak_unique_abun_df <- ak_unique_rbind

ro_unique_abun_df <- ro_unique_rbind


# function to format relative abundance table with families as rows
# and hosts as columns
make_relabun_table <- function (rbind_df, habitat) {
  
  abun_df <- rbind_df %>%
    group_by(Host, Family) %>%
    # calculate the sum of relative abundance values for a single family within
    # a host (ex. if there are multiple Acaulosporaceae ASVs in koa, this
    # pools them all so that there is just one Acaulo relabun value for koa)
    summarise(rel_abun_sum=round(sum(rel_abun), digits=3)) %>%
    # swing table from long form to wide form, with families as rows and hosts
    # as columns
    dcast(Family ~ Host) %>%
    column_to_rownames('Family') %>%
    # paste habitat name before the host name
    rename_all(function(x) paste(habitat, x, sep=" "))
  
  # change NAs to 0s
  abun_df[is.na(abun_df)] <- 0
  
  return(abun_df)
  
}


# run above function
ro_unique_table <- make_relabun_table(ro_unique_abun_df, "Remnant")

ak_unique_table <- make_relabun_table(ak_unique_abun_df, "Restored")


# function to make one complete relabun table from the RO and AK tables
merge_relabun_tables <- function (ro_table, ak_table) {
  
  merged_table <- merge(ro_table, ak_table, by="row.names")
  
  merged_table <- column_to_rownames(merged_table, "Row.names")
  
  # we want the columns ordered by host (ex. Remnant A. koa, Restored A. koa...)
  # this ordering interleaves the columns that were previously all Remnant then
  # all Restored
  index <- order(c(1:ncol(ro_table), 1:ncol(ak_table)))
  
  merged_table <- merged_table[, index]
  
}


# run above function
merged_unique_relabun <- merge_relabun_tables(ro_unique_table, 
                                              ak_unique_table)


```

## Shared

```{r}

# make new copy of shared ak df
ak_shared_abun_df <- ak_shared_rbind

ro_shared_abun_df <- ro_shared_rbind


# run function from previous section to make habitat specific relative
# abundance tables
ro_shared_table <- make_relabun_table(ro_shared_abun_df, "Remnant")

ak_shared_table <- make_relabun_table(ak_shared_abun_df, "Restored")


# run function from previous section to make complete relabun table
merged_shared_relabun <- merge_relabun_tables(ro_shared_table, 
                                              ak_shared_table)


```

## Soil Host

```{r}

# make new copy of soil_host ak df
ro_soil_host_abun_df <- ro_soil_host_rbind

ak_soil_host_abun_df <- ak_soil_host_rbind


# ditto from previous section

ro_soil_host_table <- make_relabun_table(ro_soil_host_abun_df, "Remnant")

ak_soil_host_table <- make_relabun_table(ak_soil_host_abun_df, "Restored")


 
merged_soil_host_relabun <- merge_relabun_tables(ro_soil_host_table, 
                                              ak_soil_host_table)

```

## Export

```{r}

write.csv(merged_unique_relabun, file="../outputs/unique_relabun_table.csv")

write.csv(merged_shared_relabun, file="../outputs/shared_relabun_table.csv")

write.csv(merged_soil_host_relabun, file="../outputs/shared_relabun_table.csv")

```


